name: 'Register build artifacts in Platform'
description: 'Report artifact data and version produced by a GHA workflow run to the CloudBees platform.'

branding:
  icon: 'command'
  color: 'purple'

inputs:
  cloudbees-url:
    description: 'The CloudBees platform URL.'
    required: false
    default: "https://api.cloudbees.io"
  name:
    description: 'The name of the artifact.'
    required: true
  version:
    description: 'The version of the artifact.'
    required: true
  url:
    description: 'The url where the artifact version is located e.g. docker.io/myapp/myimg:1.0.0.'
    required: true
  digest:
    description: 'The artifact digest that uniquely and immutably identifies the artifact.'
    required: false
  type:
    description: 'The type of the artifact. e.g. docker, maven'
    required: false
  label:
    description: 'The list of label of the artifact.'
  repository-url:
    description: "The clone URL of the repository."
  commit:
    description: "The commit ID from the source repository."
  ref:
    description: "The ref or branch of the checked-out repository."

outputs:
  cbp_artifact_id:
    description: "The Id of registered build artifact"

runs:
  using: "docker"
  image: "docker://public.ecr.aws/l7o7z1g8/actions/gha-register-build-artifact:main-047318f70191ae3f104690604a526a9da972df27"
  env:
    CLOUDBEES_API_URL: ${{ inputs.cloudbees-url }}
    ARTIFACT_NAME: ${{ inputs.name }}
    ARTIFACT_VERSION: ${{ inputs.version }}
    ARTIFACT_URL: ${{ inputs.url }}
    ARTIFACT_DIGEST: ${{ inputs.digest }}
    ARTIFACT_TYPE: ${{ inputs.type }}
    ARTIFACT_LABEL: ${{ inputs.label }}
    ARTIFACT_REPOSITORY_URL: ${{ inputs.repository-url }}
    ARTIFACT_COMMIT: ${{ inputs.commit }}
    ARTIFACT_REF: ${{ inputs.ref }}
