= GitHub Action: Register an artifact to the CloudBees platform

Use this GitHub Action (GHA) for artifact traceability purposes to inform the CloudBees platform that an artifact version has been created, and to report build artifact data generated by a GHA workflow run.

== Inputs

[cols="2a,1a,1a,3a",options="header"]
.Input details
|===
^| Input name
^| Data type
^| Required?
^| Description

.^| `cloudbees-url`
^.^| String
^.^| Yes
| The CloudBees platform URL. Typically, this value is `"https://api.cloudbees.io"`.

.^| `cloudbees-pat`
^.^| String
^.^| Yes
| The link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/workflows/personal-access-token[CloudBees platform personal access token].

.^| `name`
^.^| String
^.^| Yes
| The name of the artifact to send to the CloudBees platform for artifact traceability purposes.

.^| `version`
^.^| String
^.^| Yes
| The version of the artifact to send to the CloudBees platform for artifact traceability purposes.

.^| `url`
^.^| String
^.^| Yes
| The URL where the artifact version can be pulled for deployment. 

.^| `digest`
^.^| String
^.^| No
| The artifact digest that uniquely identifies the artifact.

.^| `type`
^.^| String
^.^| No
| The type of the artifact, such as Docker or Maven.
|===


== Usage examples

The following is a basic example for using the v2 action:

[source,yaml]
----
steps:
      - name: register-artifact-step
        uses: cloudbees-gha-cbp/register-build-artifact@v2
        with:
          cloudbees-url: "https://api.cloudbees.io"
          cloudbees-pat: ${{ secrets.CloudBees-platform-PAT }}
          name: my-artifact
          version: 1.0.0
          url: "https://my-artifact-url.com"

----

The following example specifies the artifact digest:

[source,yaml]
----
steps:
      - name: register-artifact-step-digest
        uses: cloudbees-gha-cbp/register-build-artifact@v2
        with:
          cloudbees-url: "https://api.cloudbees.io"
          cloudbees-pat: ${{ secrets.CloudBees-platform-PAT }}
          name: my-Docker-artifact
          version: 1.0.0
          url: "https://hub.docker.com/repository/docker/example"
          digest: "sha256:abcdef1234567890"
          type: "Docker"

----

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/third-party-ci-services/github/index[Using GitHub Actions with the CloudBees platform].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
