= GitHub Action: Register an artifact to the CloudBees platform

Use this GitHub Action (GHA) for artifact traceability purposes to inform the CloudBees platform that an artifact version has been created, and to report build artifact data generated by a GHA workflow run.

== Inputs

[cols="22%a,15%a,15%a,48%a",options="header"]
.Input details
|===
| Input name
| Data type
| Required?
| Description

| `cloudbees-url`
| String
| Yes
| The CloudBees platform URL. Typically, this value is `"https://api.cloudbees.io"`.

| `cloudbees-pat`
| String
| Yes
| The link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/workflows/personal-access-token[CloudBees platform personal access token].

| `name`
| String
| Yes
| The name of the artifact to send to the CloudBees platform for artifact traceability purposes.

| `version`
| String
| Yes
| The version of the artifact to send to the CloudBees platform for artifact traceability purposes.

| `url`
| String
| Yes
| The URL where the artifact version can be pulled for deployment.

| `digest`
| String
| No
| The artifact digest that uniquely identifies the artifact.

| `type`
| String
| No
| The type of artifact, such as Docker or Maven.

|===


== Usage examples

The following is a basic example for using the v2 action:

[source,yaml]
----
    steps:
      - name: register-artifact-step
        uses: cloudbees-gha-cbp/register-build-artifact@v2
        with:
          cloudbees-url: "https://api.cloudbees.io"
          cloudbees-pat: ${{ secrets.CloudBees-platform-PAT }}
          name: my-artifact
          version: 1.0.0
          url: "https://my-artifact-url.com"

----

The following example specifies the artifact digest:

[source,yaml]
----
    steps:
      - name: register-artifact-step-digest
        uses: cloudbees-gha-cbp/register-build-artifact@v2
        with:
          cloudbees-url: "https://api.cloudbees.io"
          cloudbees-pat: ${{ secrets.CloudBees-platform-PAT }}
          name: my-Docker-artifact
          version: 1.0.0
          url: "https://hub.docker.com/repository/docker/example"
          digest: "sha256:abcdef1234567890"
          type: "Docker"

----

=== Full workflow and run example

The following GHA workflow example uses version v2 of this action.
Running this workflow creates an artifact that is reported to the platform, and the artifact is shown as published by the GHA workflow.

.Example GHA workflow YAML file
[.collapsible]
--

[source, yaml,role="default-expanded"]
----
name: GHA Workflow

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Compile Code
        run: echo "Compiling..."

      - name: Produce Binary
        run: sleep 10

      - name: Push binary
        run: echo "Pushing Binary to ECR..."

      - name: Register Build Artifacts in Cloudbees Platform
        uses: cloudbees-gha-cbp/register-build-artifact@v2
        id: go-action
        with:
          name: "gha-artifact-test"
          version: 1.0.0
          url: "docker.io/example:latest"
          digest: "sha256:1234567890abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqr"
          type: "docker"
          cloudbees-url: "https://api.cloudbees.io"
          cloudbees-pat: ${{ secrets.CBP_PAT }}
  deploy:
    runs-on: ubuntu-latest
    needs: [build]   # Depends on 'build' job
    steps:
      - name: Checkout to Prepare Manifest
        uses: actions/checkout@v3

      - name: Trigger Deployment
        run: echo "Invoking CBP Deploy Workflow..."
----
--

After the run has completed, the artifact information is displayed in both the *Artifacts* list and the *Build artifacts* tab of *Run details* in the platform.
The artifact is shown to be published by the GHA workflow.

== License

This code is made available under the 
link:https://opensource.org/license/mit/[MIT license].

== References

* Learn more about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/using-a-different-ci/github-actions/[Using GitHub Actions with the CloudBees platform].
* Learn about link:https://docs.cloudbees.com/docs/cloudbees-platform/latest/[the CloudBees platform].
